server:
  port: 80
spring:
  application:
    name: cloud-order-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    #表示自己将注册进eureka
    register-with-eureka: true
    #从server抓取已有的注册信息
    fetch-registry: true

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  level:
    com.mzw.consumerfeign.service.GarbageCarService: debug

feign:
  hystrix:
    enabled: true