#redis
spring:
  redis:
    lettuce:
      pool:
        # 连接池最大连接数（负值无限制）
        max-active: 200
        # 最大等待时间（负值无限制）
        max-wait: -1
        # 最大空闲连接
        max-idle: 8
        # 最小空闲连接
        min-idle: 0
    host: 192.168.2.128
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 1000
    password: 123456