server:
  port: 8001
spring:
  application:
    name: cloud-hystrix-payment

eureka:
  instance:
    instance-id: payment8001
    #显示访问路径ip
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    #表示自己将注册进eureka
    register-with-eureka: true
    #从server抓取已有的注册信息
    fetch-registry: true




